### ISSUE TITLE
clover界面触控板水平反向

### ISSUE THREAD

**Issue by Julian-OU** [CrazyPegasus/ThinkPad-P1-gen2-Hackintosh#1]
在clover界面使用触控板时，指针在水平方向与手指移动方向相反，垂直方向不会出现此问题

**Comment by CrazyPegasus** [comment]
sorry,我本人没这台机器，我是应群友要求帮做的一个efi引导，细节部分不参与，需要有这机器的自己研究细节部分。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "812610357"<notifications@github.com&gt;; 
发送时间: 2020年6月1日(星期一) 中午1:51
收件人: "CrazyPegasus/ThinkPad-P1-gen2-Hackintosh"<ThinkPad-P1-gen2-Hackintosh@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [CrazyPegasus/ThinkPad-P1-gen2-Hackintosh] clover界面触控板水平反向 (#1)





 
在clover界面使用触控板时，指针在水平方向与手指移动方向相反，垂直方向不会出现此问题
